name: PHP tests

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run phpstan
      run: vendor/bin/phpstan analyse -c phpstan.neon

    - name: Run phpunit
      run: vendor/bin/phpunit -c phpunit.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: tests/results/**/*.xml
        report_individual_runs: "true"
